name: export-and-branch-solution
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:

jobs:
  export-from-dev:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: 'https://org1c23d9b2.crm3.dynamics.com/'
        user-name: 'NishB@Nishtestcompany.onmicrosoft.com'
        password-secret: ${{ secrets.password }}

    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: 'https://org1c23d9b2.crm3.dynamics.com/'
        user-name: 'NishB@Nishtestcompany.onmicrosoft.com'
        password-secret: ${{ secrets.password }}
        solution-name: TestSolution2
        solution-output-file: out/exported/TestSolution3.zip

   

   

    - name: branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@v0
      with:
        solution-folder: out/exported/TestSolution3.zip
        solution-target-folder: out/exported/TestSolution3
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true
